## Datetime Index Functionality in Pandas

Datetime Index functionality in Pandas refers to the ability to use date and time values as the index of a DataFrame , allowing efficient time-based data selection, filtering, resampling, and analysis.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('C:\\Users\\abhishek\\Downloads\\student_study_data.csv')
df

         Date  Student ID  Class Section  Study Hrs  Percentage
0  01-01-2026      1001.0     10       A        2.0        65.0
1  02-01-2026      1002.0     10     NaN        NaN        70.0
2  03-01-2026         NaN     10     NaN        4.0        75.0
3  04-01-2026         NaN     10     NaN        1.0         NaN
4  05-01-2026      1005.0     10       B        5.0         NaN
5  06-01-2026         NaN     10       A        6.0         NaN
6  07-01-2026      1007.0     10       C        2.5        68.0
7  08-01-2026      1008.0     10       B        NaN        72.0
8  09-01-2026      1009.0     10       A        NaN        80.0
9  10-01-2026      1010.0     10       C        5.5        88.0

In [4]:
df.dtypes

Date           object
Student ID    float64
Class           int64
Section        object
Study Hrs     float64
Percentage    float64
dtype: object

In [5]:
type(df.Date[0])

str

## Parse_dates

It is use to change data type of date column.

In [6]:
df = pd.read_csv('C:\\Users\\abhishek\\Downloads\\student_study_data.csv', parse_dates =['Date'])
df

        Date  Student ID  Class Section  Study Hrs  Percentage
0 2026-01-01      1001.0     10       A        2.0        65.0
1 2026-02-01      1002.0     10     NaN        NaN        70.0
2 2026-03-01         NaN     10     NaN        4.0        75.0
3 2026-04-01         NaN     10     NaN        1.0         NaN
4 2026-05-01      1005.0     10       B        5.0         NaN
5 2026-06-01         NaN     10       A        6.0         NaN
6 2026-07-01      1007.0     10       C        2.5        68.0
7 2026-08-01      1008.0     10       B        NaN        72.0
8 2026-09-01      1009.0     10       A        NaN        80.0
9 2026-10-01      1010.0     10       C        5.5        88.0

In [7]:
df.dtypes

Date          datetime64[ns]
Student ID           float64
Class                  int64
Section               object
Study Hrs            float64
Percentage           float64
dtype: object

In [8]:
type(df.Date[0])

pandas._libs.tslibs.timestamps.Timestamp