## Pandas Merging Function ()

In [1]:
import pandas as pd

#### Pandas Merge funtion conects columns or indexes in Dataframe based on one or more keys.

In [1]:
import pandas as pd

### Creating DataFrames

In [2]:
df1 = pd.DataFrame({'ID' :[1,2,3,4], 
                  'Class': [9,10,11,12]})
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [3]:
df2 = pd.DataFrame({'ID': [1,2,3,5],
                   'Name':['A','B','C','D']})
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   5    D

### Merge

In [4]:
# on parameter
pd.merge(df1,df2, on = 'ID')

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C

### Changing Position of Coloumn (left,right parameter)

In [5]:
pd.merge(df2,df1, on = 'ID')

   ID Name  Class
0   1    A      9
1   2    B     10
2   3    C     11

### If coloumn(ID) is not similar

In [6]:
pd.merge(df1, df2, on ='ID')

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C

### Inner Merge ( common in both database)

In [7]:

pd.merge(df1, df2, on ='ID' , how ='inner')

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C

### Left Merge

In [8]:
pd.merge(df1, df2, on ='ID' , how ='left')

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C
3   4     12  NaN

### Right Merge

In [9]:
pd.merge(df1, df2, on ='ID' , how ='right')

   ID  Class Name
0   1    9.0    A
1   2   10.0    B
2   3   11.0    C
3   5    NaN    D

### Outer Merge (all different values)

In [10]:
pd.merge(df1, df2, on ='ID' , how ='outer')

   ID  Class Name
0   1    9.0    A
1   2   10.0    B
2   3   11.0    C
3   4   12.0  NaN
4   5    NaN    D

### Outer Merge indicator

In [11]:
pd.merge(df1, df2, on ='ID' , how ='outer',indicator = True)   #left=df1 #right=df2

   ID  Class Name      _merge
0   1    9.0    A        both
1   2   10.0    B        both
2   3   11.0    C        both
3   4   12.0  NaN   left_only
4   5    NaN    D  right_only

### Multi index

In [12]:
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [13]:
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   5    D

In [14]:
df2 = pd.DataFrame({'ID': [5,6,7,8],
                   'Name':['A','B','C','D']})
df2

   ID Name
0   5    A
1   6    B
2   7    C
3   8    D

In [15]:
pd.merge(df1,df2, left_index = True, right_index = True)

   ID_x  Class  ID_y Name
0     1      9     5    A
1     2     10     6    B
2     3     11     7    C
3     4     12     8    D

### If Both Dataframe are Same

In [16]:
df1 = pd.DataFrame({'ID' :[1,2,3,4], 
                  'Class': [9,10,11,12]})
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [17]:
df2 = pd.DataFrame({'ID' :[1,2,3,4], 
                  'Class': [9,10,11,12]})
df2

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

### Suffixes

In [18]:
pd.merge(df1,df2, on = 'ID', suffixes =('_Higher','_Middle'))

   ID  Class_Higher  Class_Middle
0   1             9             9
1   2            10            10
2   3            11            11
3   4            12            12