## Pandas Concat Function()

Pandas concat() function is used to combine two or more DataFrames either row-wise or column-wise.

In [1]:
import pandas as pd

### Creating a Series

In [2]:
sr1 = pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [3]:
sr2 = pd.Series([3,4,5])
sr2

0    3
1    4
2    5
dtype: int64

### Concat a Series

In [4]:
pd.concat([sr1,sr2])

0    0
1    1
2    2
0    3
1    4
2    5
dtype: int64

### Concat enqual value Series

In [5]:
sr1 = pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [6]:
sr2 = pd.Series([3,4,5,6,7])
sr2

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [7]:
pd.concat([sr1,sr2])

0    0
1    1
2    2
0    3
1    4
2    5
3    6
4    7
dtype: int64

### Concat DataFrame

In [8]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
             'Name':['A','B','C','D'],
             'Class': [5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [9]:
df2 = pd.DataFrame({'ID':[5,6,7,8],
             'Name':['E','F','G','H'],
             'Class': [9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [10]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

### Changing Position of Dataframe

In [11]:
pd.concat([df2,df1])

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

### Concat Columns Wise (axis=1)

In [12]:
pd.concat([df2,df1], axis = 1)

   ID Name  Class  ID Name  Class
0   5    E      9   1    A      5
1   6    F     10   2    B      6
2   7    G     11   3    C      7
3   8    H     12   4    D      8

### Concat Rows Wise (axis=0)

In [13]:
pd.concat([df2,df1], axis = 0)

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [14]:
pd.concat([df1,df2], axis = 0, ignore_index = True)

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
4   5    E      9
5   6    F     10
6   7    G     11
7   8    H     12

## Unequal Dataframe Concat

In [15]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
             'Name':['A','B','C','D'],
             'Class': [5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [16]:
df2 = pd.DataFrame({'ID':[3,4],
             'Name':['C','D'],
             'Class': [7,8]})
df2

   ID Name  Class
0   3    C      7
1   4    D      8

In [17]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   3    C      7
1   4    D      8

In [18]:
pd.concat([df1,df2], axis = 1)

   ID Name  Class   ID Name  Class
0   1    A      5  3.0    C    7.0
1   2    B      6  4.0    D    8.0
2   3    C      7  NaN  NaN    NaN
3   4    D      8  NaN  NaN    NaN

### pd.concat() with axis=1 and inner join

In [19]:
pd.concat([df1,df2], axis = 1,join = 'inner')

   ID Name  Class  ID Name  Class
0   1    A      5   3    C      7
1   2    B      6   4    D      8

### Pandas Concat Function and Join Operations

In [26]:
# pd.concat([df1, df2], axis = 1, join_axes = [df2.index])

In [24]:
pd.concat([df1, df2], axis=1).reindex(df2.index)

   ID Name  Class   ID Name  Class
0   1    A      5  3.0    C    7.0
1   2    B      6  4.0    D    8.0

### keys Parameters (Multiple Dataframe Separated)

In [27]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
             'Name':['A','B','C','D'],
             'Class': [5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [29]:
df2 = pd.DataFrame({'ID':[5,6,7,8],
             'Name':['E','F','G','H'],
             'Class': [9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [30]:
pd.concat([df1, df2], keys = ['df1','df2'])

       ID Name  Class
df1 0   1    A      5
    1   2    B      6
    2   3    C      7
    3   4    D      8
df2 0   5    E      9
    1   6    F     10
    2   7    G     11
    3   8    H     12

In [31]:
pd.concat([df1, df2], keys = ['First df1','Second df2'])

              ID Name  Class
First df1  0   1    A      5
           1   2    B      6
           2   3    C      7
           3   4    D      8
Second df2 0   5    E      9
           1   6    F     10
           2   7    G     11
           3   8    H     12

In [32]:
pd.concat([df1, df2], axis =1, keys = ['First df1','Second df2'])

  First df1            Second df2
         ID Name Class         ID Name Class
0         1    A     5          5    E     9
1         2    B     6          6    F    10
2         3    C     7          7    G    11
3         4    D     8          8    H    12

### Different Column Names

In [33]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
             'Name':['A','B','C','D'],
             'Class': [5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [35]:
df2 = pd.DataFrame({'Marks': [40,60,80,100]})
df2

   Marks
0     40
1     60
2     80
3    100

In [36]:
pd.concat([df1,df2])

    ID Name  Class  Marks
0  1.0    A    5.0    NaN
1  2.0    B    6.0    NaN
2  3.0    C    7.0    NaN
3  4.0    D    8.0    NaN
0  NaN  NaN    NaN   40.0
1  NaN  NaN    NaN   60.0
2  NaN  NaN    NaN   80.0
3  NaN  NaN    NaN  100.0