## Pandas Join Function ()

The join() function in Pandas is used to combine two DataFrames based on their index or a key column.

In [1]:
import pandas as pd

### Creating Two Dataframe

In [10]:
df1 = pd.DataFrame({'A': [1,2,3],
                    'B':[10,20,30]})
df2 = pd.DataFrame({'C': [4,5,6],
                    'D':[40,50,60]})
display(df1,df2)

   A   B
0  1  10
1  2  20
2  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [11]:
df1.join(df2)

   A   B  C   D
0  1  10  4  40
1  2  20  5  50
2  3  30  6  60

## Different Index Dataframe

In [13]:
df1 = pd.DataFrame({'A': [1,2,3],
                    'B':[10,20,30] }, index = ['a','b','c'])
df2 = pd.DataFrame({'C': [4,5,6],
                    'D':[40,50,60]})
display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [18]:
df1.join(df2)

   A   B  C   D
a  1  10  4  40
b  2  20  5  50
c  3  30  6  60

In [22]:
df1 = pd.DataFrame({'A': [1,2,3],
                    'B':[10,20,30] }, index = ['a','b','c'])
df2 = pd.DataFrame({'C': [4,5],
                    'D':[40,50] },  index = ['a','b'])
display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
a  4  40
b  5  50

In [23]:
df1.join(df2)

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

### Right Join

In [24]:
df1.join(df2, how = 'right')

   A   B  C   D
a  1  10  4  40
b  2  20  5  50

### Outer Join

In [25]:
df1.join(df2, how = 'outer')

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

### Same Column Name

In [5]:
df1 = pd.DataFrame({'A': [1,2,3],
                    'B':[10,20,30] }, index = ['a','b','c'])
df2 = pd.DataFrame({'A': [4,5],
                    'D':[40,50] },  index = ['a','b'])
display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   A   D
a  4  40
b  5  50

In [6]:
df1.join(df2, how='outer', lsuffix='_left', rsuffix='_right')

   A_left   B  A_right     D
a       1  10      4.0  40.0
b       2  20      5.0  50.0
c       3  30      NaN   NaN