## Pandas GroupBy ()

 GroupBy() in Pandas is used to group rows having the same valuesin a column and perform aggregate operations like sum, mean, count, etc. on those groups.

In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('C:\\Users\\abhishek\\Downloads\\student_social_study.csv')
df

   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201       A     10          2                        3          65
1         202       B     10          4                        2          78
2         203       C     11          4                        5          72
3         204       A     11          5                        1          88
4         205       A     12          3                        5          55

### Group Data for Column label 1

In [34]:
grp1 = df.groupby(by = 'Section')
grp1

In [42]:
gr.groups      #Sec A,B,C index

{'A': [0, 3, 4], 'B': [1], 'C': [2]}

### Group Data for Multiple Column label 2

In [36]:
grp1 = df.groupby(['Section','Class']).groups
grp1

{('A', 10): [0], ('A', 11): [3], ('A', 12): [4], ('B', 10): [1], ('C', 11): [2]}

In [45]:
gr1 = df.groupby("Section")

for Section, df_1 in gr1:
    print(Section)
    print(df_1)

A
   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201       A     10          2                        3          65
3         204       A     11          5                        1          88
4         205       A     12          3                        5          55
B
   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
1         202       B     10          4                        2          78
C
   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
2         203       C     11          4                        5          72

In [46]:
for Class, df_1 in gr1:
    print(Class)
    print(df_1)

A
   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201       A     10          2                        3          65
3         204       A     11          5                        1          88
4         205       A     12          3                        5          55
B
   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
1         202       B     10          4                        2          78
C
   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
2         203       C     11          4                        5          72

In [47]:
dict(list(gr1))

{'A':    Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
 0         201       A     10          2                        3          65
 3         204       A     11          5                        1          88
 4         205       A     12          3                        5          55,
 'B':    Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
 1         202       B     10          4                        2          78,
 'C':    Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
 2         203       C     11          4                        5          72}

In [48]:
gr3 = df.groupby('Class').get_group(10)
gr3

   Student ID Section  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201       A     10          2                        3          65
1         202       B     10          4                        2          78

### Sum

In [50]:
gr1.sum()

         Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
Section
A               610     33         10                        9         208
B               202     10          4                        2          78
C               203     11          4                        5          72

## Mean

In [52]:
gr1.mean()

         Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
Section
A        203.333333   11.0   3.333333                      3.0   69.333333
B        202.000000   10.0   4.000000                      2.0   78.000000
C        203.000000   11.0   4.000000                      5.0   72.000000

### Describe

In [57]:
gr1.describe()

        Student ID                                                           \
             count        mean       std    min    25%    50%    75%    max
Section
A              3.0  203.333333  2.081666  201.0  202.5  204.0  204.5  205.0
B              1.0  202.000000       NaN  202.0  202.0  202.0  202.0  202.0
C              1.0  203.000000       NaN  203.0  203.0  203.0  203.0  203.0

        Class        ... Social Media Usage Hour      Percentage             \
        count  mean  ...                     75%  max      count       mean
Section              ...
A         3.0  11.0  ...                     4.0  5.0        3.0  69.333333
B         1.0  10.0  ...                     2.0  2.0        1.0  78.000000
C         1.0  11.0  ...                     5.0  5.0        1.0  72.000000


               std   min   25%   50%   75%   max
Section
A        16.921387  55.0  60.0  65.0  76.5  88.0
B              NaN  78.0  78.0  78.0  78.0  78.0
C              NaN  72.0  72.0  72.0  72.0  72.0

[3 rows x 40 columns]

### Aggregation Method

In [61]:
grp1.agg(['sum','max','mean'])

        Student ID                  Class           Study Hrs                \
               sum  max        mean   sum max  mean       sum max      mean
Section
A              610  205  203.333333    33  12  11.0        10   5  3.333333
B              202  202  202.000000    10  10  10.0         4   4  4.000000
C              203  203  203.000000    11  11  11.0         4   4  4.000000

        Social Media Usage Hour          Percentage
                            sum max mean        sum max       mean
Section
A                             9   5  3.0        208  88  69.333333
B                             2   2  2.0         78  78  78.000000
C                             5   5  5.0         72  72  72.000000

In [62]:
grp1 = df.groupby("Section")
result = grp1.agg(['sum','max','mean'])
print(result)

        Student ID                  Class           Study Hrs                \
               sum  max        mean   sum max  mean       sum max      mean
Section
A              610  205  203.333333    33  12  11.0        10   5  3.333333
B              202  202  202.000000    10  10  10.0         4   4  4.000000
C              203  203  203.000000    11  11  11.0         4   4  4.000000

        Social Media Usage Hour          Percentage
                            sum max mean        sum max       mean
Section
A                             9   5  3.0        208  88  69.333333
B                             2   2  2.0         78  78  78.000000
C                             5   5  5.0         72  72  72.000000