## Loc & iLoc

loc is used to select data by row and column labels (names).   
iloc is used to select data by integer position (row number & column number).

In [3]:
import pandas as pd

In [7]:
df = pd.read_csv('C:\\Users\\abhishek\\Downloads\\student_social_study.csv')
df

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201     10        2.0                      3.0          65
1         202     10        4.0                      2.0          78
2         203     11        3.5                      4.5          72
3         204     11        5.0                      1.0          88
4         205     12        1.5                      5.0          55

## Loc (Label Based)

In [11]:
df.loc[0]

Student ID                 201.0
Class                       10.0
Study Hrs                    2.0
Social Media Usage Hour      3.0
Percentage                  65.0
Name: 0, dtype: float64

In [12]:
df.iloc[4]

Student ID                 205.0
Class                       12.0
Study Hrs                    1.5
Social Media Usage Hour      5.0
Percentage                  55.0
Name: 4, dtype: float64

### Lists or Array of labels

In [13]:
df.loc[[0,1]]

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201     10        2.0                      3.0          65
1         202     10        4.0                      2.0          78

In [14]:
df.loc[[2,4]]

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
2         203     11        3.5                      4.5          72
4         205     12        1.5                      5.0          55

In [16]:
int   (df.loc[4,'Class'] )

12

In [17]:
df.loc[0:3,'Class']

0    10
1    10
2    11
3    11
Name: Class, dtype: int64

In [18]:
df.loc[0:2,'Percentage']

0    65
1    78
2    72
Name: Percentage, dtype: int64

In [24]:
df.loc[[ False,  False, True, False, False ]]

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
2         203     11        3.5                      4.5          72

In [25]:
df.loc[df['Class'] < 11,['Percentage']]

   Percentage
0          65
1          78

## iLoc (Index based)

In [27]:
df.iloc[0]

Student ID                 201.0
Class                       10.0
Study Hrs                    2.0
Social Media Usage Hour      3.0
Percentage                  65.0
Name: 0, dtype: float64

In [28]:
df.iloc[[0]]

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201     10        2.0                      3.0          65

In [29]:
df.iloc[[0,1]]

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201     10        2.0                      3.0          65
1         202     10        4.0                      2.0          78

In [31]:
df.iloc[[True, False, True, False,False]]

   Student ID  Class  Study Hrs  Social Media Usage Hour  Percentage
0         201     10        2.0                      3.0          65
2         203     11        3.5                      4.5          72